liblineage: Unbreak it (again)
sebaubuntu-python/liblineage pull request #17
Opened 2023-12-28 17:55 UTC by ItsVixano

* Following the changes on https://github.com/LineageOS/lineage_wiki/commit/858d862ad4127a5c2928c87a287748657adbd7b0

Change-Id: Id1cd2f06c600f0afca8b0e1f898c051a5fecfdc1

2023-12-28 22:45 UTC, SebaUbuntu requested changes

2023-12-28 22:45 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +	             kernel: Union[KernelData],
Optional[KernelData]?

2023-12-29 10:09 UTC, ItsVixano commented on liblineage/wiki/device_data.py
> +	             kernel: Union[KernelData],
Done

2023-12-29 14:07 UTC, SebaUbuntu requested changes

2023-12-29 14:07 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +	- kernel: Kernel repository & Kernel version
`kernel: Kernel info`

2023-12-29 14:07 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +from typing import Any, Dict, Optional, List, Sequence, Union
Alphabetical order

2023-12-29 14:07 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +from liblineage.wiki.data_types.kernel_data import KernelData
Alphabetical order

2023-12-29 14:07 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +			"Kernel repository": f"{GITHUB_ORG_URL}/{self.kernel.repo}",
Use `self._print_data`, and use only one line (do it like the Bluetooth one)

2023-12-29 22:29 UTC, ItsVixano commented on liblineage/wiki/device_data.py
> +			"Kernel repository": f"{GITHUB_ORG_URL}/{self.kernel.repo}",
Done

2023-12-29 23:06 UTC, SebaUbuntu approved these changes

2023-12-29 23:07 UTC, SebaUbuntu requested changes

2023-12-29 23:07 UTC, SebaUbuntu commented on liblineage/wiki/device_data.py
> +from typing import Any, Dict, List, Optional, Sequence, Union
Optional isn't required anymore

2023-12-29 23:07 UTC, SebaUbuntu commented on liblineage/wiki/data_types/kernel_data.py
> +from typing import Dict, Optional, Union
Optional isn"t used?

2023-12-30 00:03 UTC, SebaUbuntu approved these changes

2023-12-30 00:03 UTC, merged